### ISSUE TITLE
Global Stylesheets: cannot get them working

### ISSUE THREAD

**Issue by paulkogel** [devnacho/mountain_view#35]
I forked the `mountain_view_demo` repository and extended it with one commit:
https://github.com/paulkogel/mountain_view_demo/commit/4acfde0e3325b7b2e8fda77abd037b741a8e10a4

I'm trying to import a colour variable from `app/assets/stylesheets/color.scss` in a component. I added "color" to the `mountain_view` initializer (as shown in the readme), but still get the error message `"Undefined variable $green"` both on the styleguide page as well as on a page that uses the component.

My current workaround is to add `@import "colors";` in my component, but that's not very scalable.

**Comment by kitop** [comment]
@paulkogel I'd say that doing `@import "colors";` in the components that are needed is the right way to do it.
Given, the stylesheets you import should only contain variables definitions and mixins, and not actual code. That way, the dependencies are super clear and it's less surprises occur if you ever change that file's name or the variables—you can track exactly which other files depended on it.

**Comment by paulkogel** [comment]
ah ok, thanks for the explanation!
should complete the information in the README then, it confused me a bit.

**Comment by paulkogel** [comment]
and we should add how to do it to mountain_view_demo and update it to 0.8.1 :)
i might take a look at that later.

**Comment by kitop** [comment]
Ah, yes! Documentation is a bit outdated. I'll work on that this week.
Feel free to contribute if you want :)

Thanks again for your help, and keep 'em coming!

**Comment by paulkogel** [comment]
you're very welcome :)

**Comment by jonathanrbowman** [comment]
I haven't been able to get global stylesheets to work, either, unfortunately. What I did, though, is made a file `app/assets/stylesheets/_mountain-view-imports.scss` and put my imports for different files for colors, fonts, mixins, media-queries, etc. in there.

This way, at least, I only have to worry about including one line at the top of my Mountain View components - `@import "mountain-view-imports"' - which makes it just a little bit more scalable than having multiple lines of utilities to worry about maintaining inside each of my Mountain View components.

**Comment by kitop** [comment]
@jonathanrbowman can you show an example of the way you ended up using it?

If you are including those stylesheets in `mountain_view` (via `included_stylesheets`), you shouldn't be requiring them in `application.css`, that way you avoid ending up with duplicate CSS—and they are going to be there anyway if you do `require mountain_view`
`@import` directives are great for mixings, variables, etc, anything that doesn't actually inject CSS. But for CSS my recommendation is to use a separate CSS file and require it either via `included_stylesheets` **or** in `application.css` itself.

**Comment by jonathanrbowman** [comment]
@kitop Thanks for getting back to me!

That would definitely be the best way to go, and the first thing I tried was to use the MV initializer to set the `included_stylesheets` config as shown in the ReadMe. Then, require `mountain_view` in `assets/stylesheets/application.scss`. The issue was, though, that when I tried to do something in the MV initializer like...
```
# config/initializers/mountain_view.rb

MountainView.configure do |config|
  config.included_stylesheets = ["colors", "breakpoints", "fonts"]
end
```
...and then reference any of the `$variables` declared in those stylesheets, from a MV component stylesheet... 
```
// components/card/card.scss

.c-card {
  background-color: $brand_blue;

  @include mq($from: desktop) {
    display: none;
  }
}
```
...rails would error because the variables were undefined.

So, since I'm using inuitcss for this project, in my `main.scss` file, where I have all my `@imports` for scss settings and styles, I have my individual MV components being imported after my globals as I would any other scss files, like...
```
// assets/stylesheets/main.scss

// GLOBAL SETTINGS/VARS
@import 'colors';
@import 'breakpoints';

// MOUNTAIN VIEW COMPONENTS
@import "../../components/card/card";
@import "../../components/button/button";
@import "../../components/dropdown/dropdown";
```

And my `application.scss` just has...
```
// assets/stylesheets/application.scss

 *= require main
 *= require_self
```

Doing it this way enables me to see my variables and settings from the MV component stylesheets (without code duplication and having more control over load order), but I am mostly only doing it this way because I'm not sure I fully understand how to get the `included_stylesheets` config to make my global vars available inside MV component stylesheets.

**Comment by kitop** [comment]
I see what you're saying.
Yes, definitively the README is not clear. Mixins should *not* go into the `included_stylesheets`, you should manually `@import` those. `included_stylesheets` is only for actual CSS like bootstrap, a reset, or stuff like that.

Your solution also works, and thanks for clarifying! I'll update the README regardless.

Thanks!
