### ISSUE TITLE
Component SCSS not loading

### ISSUE THREAD

**Issue by angelocordon** [devnacho/mountain_view#50]
Hi guys,

Been really loving this gem! Thanks so much for putting it together.

I'm having some style asset related issues - I have a component, and originally it had an empty SCSS file. I've deleted it but later needed to add it back. After updating it with some styles, I'm noticing that my app is not compiling with the updated stylesheet at all. I've restarted my app numerous times to no avail. 

FWIW, I'm tracing this in the sources panel in the Chrome console: 
```
/* MountainView: stylesheet not found for component 'panel' */
```
even though I have a panel.scss file in my components/panel/ folder.

Any thoughts?

Thanks so much in advance!

**Comment by kitop** [comment]
Hi @angelocordon, thanks for the kind words!

Can you create a gist or paste your file structure for that component?
A bit more context would be really helpful to debug this case!

**Comment by robcole** [comment]
Hey @kitop - I helped @angelocordon debug this earlier today (I work with him) and the issue was that he was trying to use a SCSS file extension instead of CSS.

https://github.com/devnacho/mountain_view/blob/d6c85c36b5401c6eed3097d1ad8ddbe3cb9c6041/app/assets/stylesheets/mountain_view.css.erb#L9 led me to realize that files have to be called CSS, even if they're semantically SCSS/whatever else.

I'd be happy to submit this as an issue and a PR to add other names, but also 👍 if you guys prefer to only accept CSS file extensions. The documentation is relatively clear here, but I'm sure there are other people who might get confused when semantically they're writing SCSS, but within a CSS file. 

Not a huge deal for us as it's an easy fix and convention to adopt.

Let us know - happy to help either way.

**Comment by kitop** [comment]
Hi @robcole, hi @angelocordon 
Thanks for the further explanation on the issue!

Yes, `require_asset` should not worry about the extension. The idea is that it can be used with any preprocessor that works with sprockets.

Seems like this is no longer the issue then? I'll close, but feel free to comment or open another issue if it happens again.
